version: '3'
services:
  web-spoiler-detection:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-spoiler-detection
    ports:
      - 4200:4200
    volumes:
        - "./:/root"
        - "./project/:/root/project"